name: Update all.json

on:
  push:
    branches:
      - database

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Sync database to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
        run: |
          node .github/scripts/generate-json.js
