# Workflow file for registering dad jokes from issue labels
name: Register oyajigyagu from issue labels

on:
  issues:
    types:
      - labeled


permissions:
  issues: write
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  register-oyajigyagu:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Oyajigyagu Approved'
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Sync database to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
        run: |
          node .github/scripts/sync-database.js
