# Workflow file for registering dad jokes from issue labels
name: Register oyajigyagu from issue labels

on:
  issues:
    types:
      - labeled


permissions:
  issues: write
  contents: write

jobs:
  register-oyajigyagu:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Oyajigyagu Approved'
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Install dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Acquire lock
        run: |
          node .github/scripts/acquire-lock.js

      - name: Sync database to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
        run: |
          node .github/scripts/sync-database.js

      - name: Release lock
        run: |
          node .github/scripts/release-lock.js
